apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-input
spec:
  params:
    - name: input-message
      description: message to echo
      type: string
      default: "Hello, world!"
  steps:
    - name: echo-step
      image: alpine:3.14
      script: |
        #!/bin/sh
        echo "message: $(params.input-message)"

