apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-input-result
spec:
  params:
    - name: input-message
      description: message to echo
      type: string
      default: "Hello, world! Input/Result"
  results:
    - name: output-message
      description: message echoed
  steps:
    - name: echo-step
      image: alpine:3.14
      script: |
        #!/bin/sh
        upper_message=$(echo $(params.input-message) | tr '[:lower:]' '[:upper:]')
        echo "$upper_message | tee $(results.output-message.path)" > /tekton/results/output-message

